"""feature update: roles, reviews, bot_messages, dispatcher commissions,
delivery order type, split car fields.

Adds everything introduced by requirements 1–14 that is not already present in
the initial schema. Written by hand (not autogenerated) so it applies cleanly
on top of an existing production database that was created from revision 0001.

All operations are guarded / additive so the migration is safe to run against
a database that already has some of the new objects (e.g. created via
`Base.metadata.create_all`).

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def _has_column(insp, table: str, column: str) -> bool:
    try:
        return column in {c["name"] for c in insp.get_columns(table)}
    except Exception:
        return False


def _has_table(insp, table: str) -> bool:
    return table in insp.get_table_names()


def upgrade() -> None:
    bind = op.get_bind()
    insp = inspect(bind)

    # --- users: new role / car / rating columns ---------------------------
    if not _has_column(insp, "users", "granted_roles"):
        op.add_column("users", sa.Column("granted_roles", sa.String(120),
                      nullable=False, server_default="passenger"))
    if not _has_column(insp, "users", "car_color"):
        op.add_column("users", sa.Column("car_color", sa.String(60), nullable=True))
    # car_model / car_number already exist in 0001; nothing to split further.

    # --- orders: dispatcher + order type ----------------------------------
    if not _has_column(insp, "orders", "dispatcher_id"):
        op.add_column("orders", sa.Column("dispatcher_id", sa.Integer(), nullable=True))
        try:
            op.create_foreign_key(
                "fk_orders_dispatcher", "orders", "users",
                ["dispatcher_id"], ["id"],
            )
        except Exception:
            pass
    if not _has_column(insp, "orders", "order_type"):
        op.add_column("orders", sa.Column("order_type", sa.String(20),
                      nullable=False, server_default="regular"))

    # --- reviews ----------------------------------------------------------
    if not _has_table(insp, "reviews"):
        op.create_table(
            "reviews",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("order_id", sa.Integer(), sa.ForeignKey("orders.id", ondelete="CASCADE"), nullable=False),
            sa.Column("driver_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False, index=True),
            sa.Column("passenger_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
            sa.Column("stars", sa.Integer(), nullable=False),
            sa.Column("text", sa.Text(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        )

    # --- bot_messages -----------------------------------------------------
    if not _has_table(insp, "bot_messages"):
        op.create_table(
            "bot_messages",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("key", sa.String(80), nullable=False, unique=True, index=True),
            sa.Column("text", sa.Text(), nullable=True),
            sa.Column("file_id", sa.String(255), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        )

    # --- dispatcher_commissions ------------------------------------------
    if not _has_table(insp, "dispatcher_commissions"):
        op.create_table(
            "dispatcher_commissions",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("order_id", sa.Integer(), sa.ForeignKey("orders.id", ondelete="CASCADE"), nullable=False),
            sa.Column("dispatcher_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False, index=True),
            sa.Column("driver_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False, index=True),
            sa.Column("amount", sa.Numeric(10, 2), nullable=False, server_default="0"),
            sa.Column("is_paid", sa.Boolean(), nullable=False, server_default=sa.false()),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        )

    # Backfill granted_roles from the current single role for existing users.
    op.execute(
        "UPDATE users SET granted_roles = "
        "CASE WHEN role = 'passenger' THEN 'passenger' "
        "ELSE 'passenger,' || role END "
        "WHERE granted_roles IS NULL OR granted_roles = 'passenger'"
    )


def downgrade() -> None:
    bind = op.get_bind()
    insp = inspect(bind)
    if _has_table(insp, "dispatcher_commissions"):
        op.drop_table("dispatcher_commissions")
    if _has_table(insp, "bot_messages"):
        op.drop_table("bot_messages")
    if _has_table(insp, "reviews"):
        op.drop_table("reviews")
    if _has_column(insp, "orders", "order_type"):
        op.drop_column("orders", "order_type")
    if _has_column(insp, "orders", "dispatcher_id"):
        try:
            op.drop_constraint("fk_orders_dispatcher", "orders", type_="foreignkey")
        except Exception:
            pass
        op.drop_column("orders", "dispatcher_id")
    if _has_column(insp, "users", "car_color"):
        op.drop_column("users", "car_color")
    if _has_column(insp, "users", "granted_roles"):
        op.drop_column("users", "granted_roles")
