ALTER TABLE orders ADD COLUMN IF NOT EXISTS declined_driver_ids TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS decline_reasons_json TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS last_decline_reason VARCHAR(40);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_name VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_phone VARCHAR(64);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS driver_departed_at TIMESTAMPTZ;
